package Basic.HashCode;

import java.util.*;

public class Main {

	public static void main(String[] args) {
		
		//TOO SLOW
		String[] words = {"Welcome","to","Baeldung"};
		List<String> wordList = Arrays.asList(words);
		if (wordList.contains("to")){
			System.out.println("Yes exists");
		}
		
		//Simply put, hashCode() returns an integer value, generated by a hashing algorithm.
		//Objects that are equal (according to their equals()) must return the same hash code
		//Whenever it is invoked on the same object more than once during an execution of a Java application, 
		//hashCode() must consistently return the same value
		//If two objects are equal according to the equals(Object) method, 
		//then calling the hashCode() method on each of the two objects must produce the same value
		
		Map<User,User> users = new HashMap<User,User>();
		
		User user = new User(1L,"Enver");
		User user2 = new User(2L,"Yilmaz");
		
		users.put(user, user);
		users.put(user2,user2);
		
		if (users.containsKey(user)){
			System.out.println("User found");
			System.out.println(user);
		}
		
		
	}

}
